### ISSUE TITLE
Connection refused after HA update

### ISSUE THREAD

**Issue by laurkaarna** [jeatheak/Mitsubishi-WF-RAC-Integration#53]
After latest update of HA to version 2023.7.1 the integration stoped working. Was unavailable after update. Deleted the device and did a restart on HA and this resulted in finding my aircon but unable to add it. I get this error when seting a name for the device: 

`Could not connect with the Airco: HTTPConnectionPool(host='192.168.1.53', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67082c10>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Custom component version: V.0.4.0
Log output: 

This error originated from a custom integration.

Logger: custom_components.mitsubishi_wf_rac.config_flow
Source: custom_components/mitsubishi_wf_rac/config_flow.py:72 
Integration: mitsubishi_wf_rac (documentation) 
First occurred: July 8, 2023 at 11:48:47 PM (9 occurrences) 
Last logged: July 8, 2023 at 11:58:27 PM

create failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f64798050>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.53', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64798050>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/mitsubishi_wf_rac/config_flow.py", line 70, in _async_register_airco
    airco_id = await repository.get_airco_id()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mitsubishi_wf_rac/wfrac/repository.py", line 91, in get_airco_id
    return (await self.get_info())["airconId"]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mitsubishi_wf_rac/wfrac/repository.py", line 87, in get_info
    return (await self._post("getDeviceInfo"))["contents"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mitsubishi_wf_rac/wfrac/repository.py", line 66, in _post
    response = await self._hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.53', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64798050>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mitsubishi_wf_rac/config_flow.py", line 122, in _async_create_common
    info = await self._async_register_airco(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mitsubishi_wf_rac/config_flow.py", line 72, in _async_register_airco
    raise CannotConnect(reason=str(query_failed)) from query_failed
custom_components.mitsubishi_wf_rac.config_flow.CannotConnect

**Comment by laurkaarna** [comment]
Just started working again. Didnt do a thing, just tried to add the device again.

**Comment by jeatheak** [comment]
Hey thank you for making this issue. This is something that happens sometimes and I don't know why. The device will refuse the connection and a while later it will accept it. I think it has to do something with an already conencted account but it is difficult to test and prove. I'm glad to hear the device did connect in the end.

I will close this issue for now. If it happens to more people I will re-open it.
